name: Lint
on:
  pull_request:
    branches: ['main']

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint
        run: |
          npm install --legacy-peer-deps
          npm run lint:ci
